# Generated by Django 4.1.6 on 2023-05-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=50)),
                ('User_email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=50)),
                ('Con_password', models.CharField(max_length=50)),
            ],
        ),
    ]
