# Generated by Django 4.1.6 on 2023-05-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0003_alter_jobpost_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='Company_logo',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
