# Generated by Django 4.1.6 on 2023-05-10 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0005_alter_jobpost_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobPost',
        ),
    ]
