# Generated by Django 4.1.6 on 2023-05-13 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0007_jobpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=50)),
                ('User_phone_number', models.CharField(max_length=50)),
                ('User_coll_univ', models.CharField(max_length=50)),
                ('User_resume', models.FileField(upload_to='user_resume/')),
                ('jobpost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobportal.jobpost')),
            ],
        ),
    ]
