# Generated by Django 4.1.6 on 2023-05-13 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0008_user_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobportal.employee'),
        ),
    ]
